# Generated by Django 4.0.4 on 2022-04-13 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id_bill', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name_category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMservicesApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id_provider', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=40, verbose_name='Name')),
                ('lastnames', models.CharField(max_length=40, verbose_name='LastNames')),
                ('cellphone', models.CharField(max_length=20, verbose_name='Cellphone')),
                ('address', models.CharField(max_length=40, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('names', models.CharField(max_length=40, verbose_name='Name')),
                ('lastnames', models.CharField(max_length=40, verbose_name='LastNames')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('cellphone', models.CharField(max_length=20, verbose_name='Cellphone')),
                ('address', models.CharField(max_length=40, verbose_name='Address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id_sale', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('id_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMservicesApp.bill')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMservicesApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='id_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMservicesApp.provider'),
        ),
        migrations.AddField(
            model_name='bill',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastChangeDate', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
