# Generated by Django 4.0.4 on 2022-04-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMservicesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='business',
            field=models.CharField(max_length=40, null=True, verbose_name='Business'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='lastnames',
            field=models.CharField(max_length=40, null=True, verbose_name='LastNames'),
        ),
    ]
